---
- name: start spark master services
  service: name={{ item }} state=started
  with_items:
  - spark-master
  tags:
  - cdh5-spark-master
#  failed_when: "'FAILED' in stdout"
- name: create /user/spark/applicationHistory
  shell: sudo -u hdfs hadoop fs -mkdir /user/spark && sudo -u hdfs hadoop fs -mkdir /user/spark/applicationHistory && sudo -u hdfs hadoop fs -chown -R spark:spark /user/spark && sudo -u hdfs hadoop fs -chmod 1777 /user/spark/applicationHistory
  tags:
  - cdh5-spark-master

- name: start spark history services
  service: name={{ item }} state=started
  with_items:
  - spark-history-server
  tags:
  - cdh5-spark-master
